USE [master]
GO

/****** Object:  Database [BookeeperPro]    Script Date: 10/17/2016 4:11:02 PM ******/
CREATE DATABASE [BookeeperPro]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookeeperPro', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\BookeeperPro.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BookeeperPro_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\BookeeperPro_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BookeeperPro] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookeeperPro].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BookeeperPro] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BookeeperPro] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BookeeperPro] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BookeeperPro] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BookeeperPro] SET ARITHABORT OFF 
GO

ALTER DATABASE [BookeeperPro] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BookeeperPro] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [BookeeperPro] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BookeeperPro] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BookeeperPro] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BookeeperPro] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BookeeperPro] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BookeeperPro] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BookeeperPro] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BookeeperPro] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BookeeperPro] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BookeeperPro] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BookeeperPro] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BookeeperPro] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BookeeperPro] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BookeeperPro] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BookeeperPro] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BookeeperPro] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BookeeperPro] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BookeeperPro] SET  MULTI_USER 
GO

ALTER DATABASE [BookeeperPro] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BookeeperPro] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BookeeperPro] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BookeeperPro] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BookeeperPro] SET  READ_WRITE 
GO

